import setuptools

setuptools.setup(
    name="basketball_stats_storage",
    version="0.1.0",
    author="Peter Connelly",
    author_email="pconnelly898@gmail.com",
    license="MIT",
    description="Common storage provider for all basketball-stats related repos",
    long_description="boop",
    long_description_content_type="text/markdown",
    url="https://github.com/SwolenOstrich430/basketball_reference_client",
    packages=setuptools.find_packages(),
    package_data={'basketball_stats_storage': ['*.txt']},
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.6",
    install_requires=[
        'basketball_stats_config @ git+https://github.com/SwolenOstrich430/basketball-stats-config@740acf8dcc8ad19c235811f4c48d87d25767cd0c',
        'blinker',
        'cachetools',
        'certifi',
        'charset-normalizer',
        'click',
        'google-api-core',
        'google-auth',
        'google-cloud-core',
        'google-cloud-storage',
        'google-crc32c',
        'google-resumable-media',
        'googleapis-common-protos',
        'idna',
        'iniconfig',
        'itsdangerous',
        'Jinja2',
        'MarkupSafe',
        'packaging',
        'pluggy',
        'proto-plus',
        'protobuf',
        'pyasn1',
        'pyasn1_modules',
        'Pygments',
        'requests',
        'rsa',
        'urllib3',
        'Werkzeug'
    ],
    extras_require={
        'test': ['pytest', 'pytest-mock'],
    },
    keywords=[
        "nba",
        "sports",
        "data mining",
        "basketball",
        "basketball reference",
        "basketball-reference.com",
    ],
)